#!/usr/bin/env python
""" eadator
    try DTD and XSD validation for EAD2002, support EAD3 as well later
"""

import sys
import argparse
from lxml import etree

def main(argv=None):

    parser = argparse.ArgumentParser( description='EAD validator')
    parser.add_argument('eadfile', nargs=1, help="EAD XML file to check" )

    if argv is None:
        argv = parser.parse_args()

# main() idiom for importing into REPL for debugging 
if __name__ == "__main__":

    sys.exit(main())
